OnlineArtGallery/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace OnlineArtGallery.Controllers
{
    public class AboutUsController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

OnlineArtGallery/Controllers/HelpsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace OnlineArtGallery.Controllers
{
    public class HelpsController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

OnlineArtGallery/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace OnlineArtGallery.Controllers
{
    public class LoginController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

OnlineArtGallery/Controllers/NewArtController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace OnlineArtGallery.Controllers
{
    public class NewArtController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

OnlineArtGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SEM3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/custom.css" />
    <!-- Load font awesome icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@1&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo-art.png" width="200" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-5">
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="NewArt">New Art</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="ArtInSale">Art In Sale</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="AboutUs">About Us</a>
                        </li>
                    </ul>
                    <form class="form-inline mt-2 mt-md-0 form-search">
                        <input class="form-control mr-sm-2 ip-search-home" style="width: 400px;" type="text" placeholder="Search by artist, product ..." aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="ContactUs">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Register"><img src="https://res.cloudinary.com/dxfq3iotg/image/upload/v1560918647/user.svg" alt="" width="17"> Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <section class="main-content">
        <main role="main" class="py-5">
            @RenderBody()
            <!-- The social media icon bar -->
            <div class="icon-bar">
                <a href="#" class="facebook"><i class="fab fa-facebook-f"></i></a>
                <a href="#" class="twitter"><i class="fab fa-twitter"></i></a>
                <a href="#" class="youtube"><i class="fab fa-youtube"></i></a>
            </div>
        </main>
    </section>
    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - SEM3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@
    <footer class="pt-2 text-muted">
        <div class="container">
            <div class="row  ">
                <div class="col-xs-6 col-sm-3">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/images/logo-art.png" width="200" />
                    </a>
                    <address class="color-light-20">
                        1600 Amphitheatre Parkway<br>
                        Mountain View, CA 94043
                    </address>
                    <ul class="list-unstyled list-light">
                        <li><a href="#">Disclaimer</a></li>
                    </ul>
                </div>

                <div class="col-xs-6 col-sm-3">
                    <h1 class="my-2">Bidding Products</h1>
                    <ul class="list-unstyled list-light text-white">
                        <li><a href="#">Indian Art</a></li>
                        <li><a href="#">Scriptures</a></li>
                        <li><a href="#">Models</a></li>
                    </ul>
                </div>
                <br style="clear:both" class="hidden-sm-up">
                <div class="col-xs-6 col-sm-3">
                    <h1 class="my-2">About Us</h1>
                    <ul class="list-unstyled list-light">
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Exhibiton</a></li>
                        <li><a href="#">Events</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
                <div class="col-xs-6 col-sm-3">
                    <h1 class="my-2">Connect</h1>
                    <ul class="list-unstyled list-light">
                        <li><a asp-action="Index" asp-controller="Helps">Helps</a></li>
                        <li><a href="#">Social</a></li>
                        <li><a href="#">Community</a></li>
                    </ul>
                </div>
            </div>
            <hr>
            <div class="row f-flex justify-content-between" style="justify-content: space-between;">
                <div class="col-md-8 text-xs-center text-left my-1">
                    <p class="mt-2 text-muted">T11907M0 - Team 2 FPT APTECH © Copyright 2020 • All Rights Reserved | <a class="" href="#">Disclaimer</a> | <a class="" href="#">Contact</a></p>
                </div>
                <div class="col-md-4 text-xs-center text-lg-right my-1">
                    <div class="btn-container  mt-1 text-md-right text-sm-center">
                        <div class="mb-1 mr-3 align-self-right pt-0 d-inline-block">
                            <a href="#" role="button" class=" btn-white p-2 m-2 btn btn-round btn-rised btn-icon x"><i class="fab fa-twitter fa-lg color-light" aria-hidden="true"></i></a>
                            <a href="#" role="button" class="btn-white p-2 m-2 btn btn-round btn-rised btn-icon"><i class="fab fa-facebook fa-lg" aria-hidden="true"></i></a>
                            <a href="#" role="button" class="btn-white p-2 m-2 btn btn-round btn-rised btn-icon"><i class="fab fa-youtube fa-lg" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/smooth-scrollbar.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>