OnlineArtGallery/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace OnlineArtGallery.Controllers
{
    public class LoginController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

OnlineArtGallery/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace OnlineArtGallery.Controllers
{
    public class RegisterController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

OnlineArtGallery/Views/Login/Index.cshtml
@{ ViewData["Title"] = "Login"; }

<section class="login-body py-5">
    <div class="container d-flex align-items-lg-center ">
        <div class="row mt-lg-5">
            <div class="col-lg-6 pl-5 pr-5">
                <div class=" text-left p-4 mb-5 bg-white my-login-container align-items-lg-center text-center">
                    <div class="container">
                        @*------------Logo------------*@
                        <img src="~/images/logo-art.png" width="70%">
                    </div>
                    <form class="pt-3">
                        @*-----------Email---------*@
                        <div class="form-group">
                            <input type="email" class="form-control " id="exampleInputEmail1" placeholder="Email">
                        </div>
                        @*-------------Password--------------*@
                        <div class="form-group">
                            <input type="password" class="form-control " id="exampleInputPassword1" placeholder="Password">
                        </div>
                        @*---------------Keep me Sign in (Form check)--------------*@
                        <div class=" d-flex justify-content-between align-items-center">
                            <div class="formcheck">
                                <label class="form-check-label text-muted">
                                    <input type="checkbox" class="form-check-success"> Keep me signed in
                                </label>
                            </div>
                            @*------------Forgot Password---------------*@
                            <a href="#" class="auth-link text-black">Forgot password?</a>
                        </div>
                        @*-------------Sign In Button------------------*@
                        <div class="mt-3">
                            <a class="btn btn-block btn-success btn-lg font-weight-medium auth-form-btn " href="../../index.html">SIGN IN</a>
                        </div>
                        <div class="my-2 d-flex justify-content-center d-inline align-items-center">
                            <strong>Or</strong>
                        </div>
                        @*-----------------Sign In with Facebook Button---------------*@
                        <div class="mb-2">
                            <button type="button" class="btn btn-block btn-facebook auth-form-btn">
                                <i class="icon-social-facebook mr-2"></i>Connect using facebook
                            </button>
                        </div>
                        @*------------------Sign In wirh Google Button---------------*@
                        <div class="mb-2">
                            <button type="button" class="btn btn-block btn-google auth-form-btn">
                                <i class="icon-social-google mr-2"></i>Connect using Google
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-6 p-5">
                <div class="container  align-items-lg-center">
                    <h1 class="text-center text-black"><strong>Don't have an account?</strong></h1>
                    @*-----------Create account Button---------------*@
                    <a class="btn btn-success m-3 btn-block my-register-btn" asp-action="Index" asp-controller="Register">Create now</a>
                    @*----------------Benefit display-----------------*@
                    <ul class="display-5 my-login-ul text-black">
                        <li><i class="fa fa-check my-checked-icon"> </i> Place your bids on any of over 50,000 exceptional items auctioned every week</li>
                        <li><i class="fa fa-check my-checked-icon"> </i> Receive an automatic notification if your selected item comes up for auction</li>
                        <li><i class="fa fa-check my-checked-icon"> </i> Sell your items through our auctions</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- content-wrapper ends -->
</section>